name: mlops-chapter1
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn=1.1.3
  - joblib
  - matplotlib
  - seaborn
  - pylint 
  - shap
  - autopep8
  - pytest